# Generated by Django 5.0 on 2024-07-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='total_consultations',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
