# Generated by Django 5.0 on 2024-05-10 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=150)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due'), ('Canceled', 'Canceled')], max_length=20)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_manager.room')),
            ],
        ),
    ]
