# Generated by Django 5.0 on 2024-06-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
