# Generated by Django 5.0 on 2024-06-06 17:17

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_specialists', models.PositiveIntegerField(default=0)),
                ('icon', models.FileField(blank=True, null=True, upload_to='specialistCategory_images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_active', 'In_Active')], default='in_active', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null='True')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profile_pics/')),
                ('languages_spoken', models.CharField(max_length=255)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_consultations', models.PositiveIntegerField(blank=True, null=True)),
                ('sunday_availability', models.BooleanField(default=False)),
                ('monday_availability', models.BooleanField(default=True)),
                ('tuesday_availability', models.BooleanField(default=True)),
                ('wednesday_availability', models.BooleanField(default=True)),
                ('thursday_availability', models.BooleanField(default=True)),
                ('friday_availability', models.BooleanField(default=True)),
                ('saturday_availability', models.BooleanField(default=True)),
                ('sunday_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('sunday_end_time', models.TimeField(default=datetime.time(13, 0))),
                ('monday_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('monday_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('tuesday_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('wednesday_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('wednesday_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('thursday_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('thursday_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('friday_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('friday_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('saturday_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('saturday_end_time', models.TimeField(default=datetime.time(13, 0))),
                ('x', models.TextField(blank=True, null='True')),
                ('whatsApp', models.TextField(blank=True, null='True')),
                ('facebook', models.TextField(blank=True, null='True')),
                ('instagram', models.TextField(blank=True, null='True')),
                ('physical_clinic', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255, null='True')),
                ('city', models.CharField(blank=True, max_length=100, null='True')),
                ('state', models.CharField(blank=True, max_length=100, null='True')),
                ('country', models.CharField(blank=True, max_length=100, null='True')),
                ('zipcode', models.CharField(blank=True, max_length=20, null='True')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialistcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('concern', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='Pending', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='CommonConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Common_Consultations_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialistcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('concern', models.CharField(blank=True, max_length=250, null=True)),
                ('feedback_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due'), ('Canceled', 'Canceled')], max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
