# Generated by Django 5.0 on 2024-06-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
