# Generated by Django 5.0 on 2024-06-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_diagnosis_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='specialist',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialists.appointment'),
        ),
    ]
