# Generated by Django 5.0 on 2024-06-11 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_remove_diagnosis_patient_remove_diagnosis_specialist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
