# Generated by Django 5.0 on 2024-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0007_alter_specialist_biography_alter_specialist_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='total_consultations',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
