# Generated by Django 5.0 on 2024-07-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0008_alter_specialist_average_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='hospitals/default.png', null=True, upload_to='hospitals/')),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('hospital_type', models.CharField(choices=[('private', 'Private hospital'), ('public', 'Public hospital')], max_length=200)),
                ('general_bed_no', models.IntegerField(blank=True, null=True)),
                ('available_icu_no', models.IntegerField(blank=True, null=True)),
                ('regular_cabin_no', models.IntegerField(blank=True, null=True)),
                ('emergency_cabin_no', models.IntegerField(blank=True, null=True)),
                ('vip_cabin_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='specialistcategory',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='specialist',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialists.hospital'),
        ),
    ]
