# Generated by Django 5.0 on 2024-07-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0009_hospital_specialistcategory_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='specializations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
