# Generated by Django 5.0 on 2024-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0010_hospital_departments_hospital_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='hospital',
        ),
        migrations.AddField(
            model_name='specialist',
            name='hospital',
            field=models.ManyToManyField(blank=True, null=True, to='specialists.hospital'),
        ),
    ]
