# Generated by Django 5.0 on 2024-07-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0015_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='pricing',
        ),
    ]
