# Generated by Django 5.0 on 2024-05-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0002_guest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
