# Generated by Django 5.0 on 2024-05-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0003_guest_cancel_reason_guest_reject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='suite',
        ),
        migrations.AddField(
            model_name='tenant',
            name='suite',
            field=models.ManyToManyField(blank=True, null=True, to='asset_manager.room'),
        ),
    ]
