# Generated by Django 5.0 on 2024-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0005_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='suite',
            field=models.ManyToManyField(to='asset_manager.room'),
        ),
    ]
