# Generated by Django 5.0 on 2024-06-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0006_alter_tenant_suite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrentpayment',
            name='payment_month',
            field=models.IntegerField(default=6),
        ),
    ]
