# Generated by Django 5.0 on 2024-06-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0007_alter_monthlyrentpayment_payment_month'),
        ('transactions', '0002_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardroombooking',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='boardroombooking',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='boardroombooking',
            name='suite',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='suite',
        ),
        migrations.RemoveField(
            model_name='monthlyrentpayment',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='room',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='suite',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='authorized_people',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='users',
        ),
        migrations.DeleteModel(
            name='BoardroomBooking',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='MonthlyRentPayment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
